name: tictactoe_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod:
  auto_route: 
  flutter_screenutil:
  flutter_svg:
  hive_ce:
  path_provider:
  intl:
  easy_localization: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_flavorizr: ^2.4.1
  flutter_native_splash:
  flutter_launcher_icons:
  auto_route_generator:
  build_runner:
  hive_ce_generator:
  json_serializable:
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  fonts:
    - family: "Joyful"
      fonts:
        - asset: assets/fonts/Super-Joyful.ttf
          weight: 400

  assets:
    - assets/image/
    - assets/icons/
    - assets/fonts/
    - assets/translations/

flavorizr:
  app:
    android:
      flavorDimensions: "env"
    ios:
      flavorDimensions: "env"

  flavors:
    dev:
      app:
        name: "TicTacToe [Dev]"
      android:
        applicationId: "com.hlcb.tictactoe.dev"
      ios:
        bundleId: "com.hlcb.tictactoe.dev"

    staging:
      app:
        name: "TicTacToe [Staging]"
      android:
        applicationId: "com.hlcb.tictactoe.staging"
      ios:
        bundleId: "com.hlcb.tictactoe.staging"

    prod:
      app:
        name: "TicTacToe"
      android:
        applicationId: "com.hlcb.tictactoe"
      ios:
        bundleId: "com.hlcb.tictactoe"